name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
    - name: Build
      working-directory: ./BeeBot
      run: dotnet build --configuration Release
    - name: Publish
      working-directory: ./BeeBot
      run: dotnet publish -c Release --no-build -o ../publish/
    - name: Fix publish
      working-directory: ./publish
      run: |
        mv wwwroot/* .
        rmdir wwwroot
        sed -i -e "s/base href=\".*\"/base href=\"\/BeeBot\/\"/" index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
